"""Rebuild the complete source-asset index without copying binary art."""
import pathlib,json
root=pathlib.Path(__file__).resolve().parents[1]
files=sorted(p.relative_to(root/'assets').as_posix() for p in (root/'assets/super').rglob('*') if p.is_file())
(root/'js/super-manifest.js').write_text('/* Generated by scripts/index-super.py; includes source files, not just sprites. */\nNR.superManifest = '+json.dumps(files,ensure_ascii=False)+';\n')
